### ISSUE TITLE
inserting a bytea

### ISSUE THREAD

**Issue by fyt000** [yandex/ozo#102]
Do you mind showing us what's the best way to insert a bytea field into the database?
`ozo::pg::bytea` does not work due to the wrapper missing `size()/data()` and we couldn't build a query with it. Thanks in advance.

**Comment by thed636** [comment]
Thanks for the report!
This is an issue with calculating `size_of()`. Specialisation for `strong_typedef_wrapper` wrapped types is missed. 
The PR with fix and test will be here shortly.

**Comment by thed636** [comment]
Pull request: https://github.com/yandex/ozo/pull/103

**Comment by fyt000** [comment]
Great, thanks a lot!

**Comment by fyt000** [comment]
Sorry to reopen it. We tried again on the branch with the pr, it looks like whats going into the database doesn't match what's coming out of it. 
Specifically, a dump of the `ozo::pg::bytea` variable pre-insertion doesn't match what's in the database post-insertion. Reading `ozo::pg::bytea` works fine.
we are using it like this
```c++
std::vector<char> salt(HASH_SIZE, 0);
std::vector<char> hashed_password(HASH_SIZE, 0);
// ...
ozo::pg::bytea salt_bytea(std::move(salt));
ozo::pg::bytea pswd_bytea(std::move(hashed_password));
ozo::execute(conn_,
                             "INSERT INTO user_id (username, hashed_password, salt) VALUES ("_SQL +
                                 id + ","_SQL + pswd_bytea + ","_SQL + salt_bytea + ")"_SQL,
                             yield[ec]);
```

**Comment by thed636** [comment]
Thanks a lot for example! ~~I'll try to reproduce this tomorrow to see what is happening and how to fix it.~~
Well, I'd reproduced it today because in other way could not sleep well. :)

The problem is what the previous fix is not correct. It leads to application of size calculation algorithm for arrays instead of default algorithm for dynamic size data.

So, I'll produce the PR with fix tomorrow, without any haste and with better tests. 
But in case if you just want to continue to work you can try this branch - [fix_strong_typedef_size_of ](https://github.com/yandex/ozo/tree/fix_strong_typedef_size_of).

**Comment by fyt000** [comment]
That's a lot of dedication LOL! The new branch works for us. Thanks again for the quick fix.

**Comment by thed636** [comment]
PR with fix is here https://github.com/yandex/ozo/pull/104

**Comment by thed636** [comment]
Merged in master
