### ISSUE TITLE
How to retrieve RAISEd error messages

### ISSUE THREAD

**Issue by JonasProgrammer** [yandex/ozo#132]
First of all, thank you for this awesome library!
I currently have an issue with getting the cause of a transaction abort within an `ozo` handler. Neither `ec.message()` nor `ozo::get_error_context` seem to do the job, however, as I just get a generic 'transaction aborted' message in both.

Basically I have something like this:
```sql
CREATE FUNCTION foo(bar int) [...]
IF bar = 42 THEN RAISE '$err1$ some message' END IF;
IF bar < 0 THEN RAISE '$err2$ other message' END IF;
[...]
```

And I'm trying to achieve this:
```cpp
ozo::begin(/*...*/, [](ozo::error_code ec, auto conn) {
  if (ec) return;
  ozo::execute(std::move(conn), "SELECT foo("_SQL + 42 + ")"_SQL, [](ozo::error_code ec, auto conn) {
    if (ec)
    {
        auto err = ec.message(); // ozo::get_error_context(conn) doesn't work either
        // if err contains $err1$ do one thing, do something else otherwise
// ...
```

Please beware that I'm using a forked version of ozo that works with boost 1.70 (and uses targets in CMake, but that shouldn't change the behaviour of a header only lib), so if this approach should work with vanilla ozo, please tell me, so I can look where I screwed up.

**Comment by thed636** [comment]
Hi Jonas!

Thanks for the issue.

Try to get native error message via [ozo::error_message()](https://yandex.github.io/ozo/group__group-connection-functions.html#gae1d570854c32a38adcad99baf73e0baa) function. Unfortunately it is not very clear since the function is not used in any example - let's do not close this issue until I've change the examples.

BTW is it possible to see the fork of the project? I'm interesting in both changes, so if this fork is yours then it would be nice to have a PR in the project.

**Comment by JonasProgrammer** [comment]
@thed636 Thanks alot, you're saving my weekend. `ozo::error_message()` works like a charm.

[Here's the fork](https://github.com/JonasProgrammer/ozo/tree/boost-170-ozo) (the branch name should have been `boost-170-conan`).

I thought about PRing, but I didn't, because this is basically what should have been 3 feature branches. At the same time this:
1. changes basically all CMake files to use targets (and breaks Coverage in doing so, as I didn't need it and couldn't be bothered to port it yet)
2. adds a conan recipe packing the 'targetized' version for CMake
3. fixes the stuff that broke with boost 1.70 (mostly trial & error in changing some typedefs; it does compile and all tests run fine, but I haven't checked, whether I introduced UB somewhere)

If you find any of these 3 useful, let me know, I can try and extract them for better separation.

**Comment by thed636** [comment]
@JonasProgrammer thanks! I didn't have time to see the fork, so I'll do it a little bit later. But, definitely, Boost 1.70 compatibility is the best feature to start with. I've made a separate issue for this #134. So you may relate on it in your PR.

It is very important for the project to have such PRs from the library users, because inside the company, obviously, the priority is given for the company-related tasks.

**Comment by thed636** [comment]
@JonasProgrammer could you please to look at the [HOWTO](https://github.com/yandex/ozo/blob/master/docs/howto.md#how-to-handle-error-properly) and the [examples](https://github.com/yandex/ozo/tree/master/examples). Is it clear enough how to obtain information about an error?

**Comment by JonasProgrammer** [comment]
Yep, it's much clearer now, especially as to which function returns what. Thanks for putting so much effort into clarifying this.
