### ISSUE TITLE
Boos 1.70 compatibility

### ISSUE THREAD

**Issue by thed636** [yandex/ozo#134]
Currently OZO does not support Boost 1.70 and this is no good.

**Comment by JonasProgrammer** [comment]
See [resource_pool#2](https://github.com/elsid/resource_pool/pull/2), as this is the very basic requirement for getting it running in 1.70.
Travis fails for the 1.70 version due to some linking errors I'm not getting when using it locally together with ozo. Perhaps you guys have an idea as to why that is.

I'll try and get the stuff from ozo itself untangled tomorrow morning.

**Comment by thed636** [comment]
Thanks for the PR, Jonas!

I think it needs some time with `resource_pool`, since it's author no longer works for Yandex. But I'm pretty sure we can manage it. So in worst case I'll ask you for two separate PRs, first one with changes in OZO only, and second one with `resource_pool` update.

I've request some minor changes from you, but it seems like PR is almost ready for the project's master.

**Comment by JonasProgrammer** [comment]
So, I hope I got everything sorted out on the PR. With the C++ changes alone it's almost diminishable, so sorry for causing extra work for you.

Regarding `resource_pool`: Out of curiosity, wouldn't a yandex-owned fork make sense for that? Not meant to be a hostile fork, but just to get ozo-related changes faster into the repo.

**Comment by thed636** [comment]
> So, I hope I got everything sorted out on the PR. With the C++ changes alone it's almost diminishable, so sorry for causing extra work for you.

Thank you very much, everything is ok now. Could you please to squash all your commits into single one and force push it? Just to make history simple and straightforward.

> Regarding resource_pool: Out of curiosity, wouldn't a yandex-owned fork make sense for that? Not meant to be a hostile fork, but just to get ozo-related changes faster into the repo.

You're absolutely right, I'm working now on this problem. There are different ways to solve it. To place a project into the organization repository is not a simple thing due to legal procedures and approvements what takes time. But anyway it will be done sooner or later. For now, I'm working on a workaround with the resource_pool owner. He is a kind person, and I do not expect any problems. So now it needs to wait for a couple of days.

**Comment by thed636** [comment]
@JonasProgrammer I've got a reply from Roman, who is the owner of `resource_pool`. He says had just returned from a trip, so he will handle your PR at least this weekend.

**Comment by fyt000** [comment]
I just found out that resource_pool is under GPL, which uhm...  `ozo` is not.

**Comment by thed636** [comment]
@three0s hi!
Yes `ozo` is published under `PostgreSQL` license to be more friendly for PostgreSQL users. `resource_pool` was published prior to `ozo` under `GPL`. On practice `resource_pool` is not a part of `ozo` - it is a dependency which is coupled by means of submodule system. That's how it is. Do you have any real problems with different licenses now? If so I'd like to have an issue with a description to have a chance to solve the problem.

**Comment by fyt000** [comment]
No, not really. I just found it weird, and potentially problematic. But I don't know enough about licenses.

**Comment by JonasProgrammer** [comment]
@thed636 The changes to `resource_pool` were merged now, I've amended the PR accordingly to include the changes to the submodule.

Regarding the licence, I'm also not sure it's technically allowed to use ozo in a non-GPL compatible environment because of this. At least stuff using the connection pooling functionality would be covered work, as far as I can tell, but IANAL.
But I think as the solely copyright holder, elsid could perhaps just dual licence it, if this really did cause issues for someone.

**Comment by thed636** [comment]
@JonasProgrammer thanks for your opinion. Well, I'll think about the license and possible solutions.

So, congratulations, thanks to you, we are now support Boost 1.70! Hooray! :)

**Comment by jonesmz** [comment]
resource_pool being GPL v3 means that any program with code from the resource_pool library linked (as in .o files being combined into dlls/exes) or compiled into it directly must also be distributed under the GPL v3 license.

If resource_pool is header-only, then any cpp file that #include's it would be subject to the GPL v3 license.

I strongly recommend that you contact Roman, the owner of resource_pool, and request he address this licensing issue.

However, Roman is not the exclusive copyright holder of the code in the resource_pool project. By my count, there are 7 contributors, including @JonasProgrammer and @thed636.

If Roman wrote resource_pool while employed by Yandex, then Roman's contributions to that library would be owned by Yandex, not Roman. In which case, it's not required to get his permission.

However, in order for a re-license to take place, all contributors / copyright owners must agree, or their contributions must be removed. Notably, any contributions that Roman made after his employment at Yandex ended will also need Romans permission, because those wouldn't be owned by Yandex.

Please let me know if you have any questions.
