### ISSUE TITLE
Reduce C++  requirement to C++11/14

### ISSUE THREAD

**Issue by raidenluikang** [yandex/ozo#146]
Why there C++17 is needed?  
Can reduce it to C++11/14 ?  

Because, C++17 is very fresh standard, where not supported most compilers.

Most common Linux servers (Centos 6/7, Debian 8/9) have old GCC compilers ( gcc 4.7, gcc 4.8, gcc 5), which are not supported C++17.

**Comment by thed636** [comment]
Hi @raidenluikang! 

Thanks for the request. Sorry, but the short answer is no.

Here is an explanation.

We chose the C++17 because we are using it in the company. We wanted to make a good library without the extra code for the older standards which we just do not need. In the opposite case, we would create a legacy code from the very beginning of the project and that's not a good strategy for us. The best strategy is to make an investment in the future not in the past. Sorry for disappointment and thanks for understanding.
