### ISSUE TITLE
connection pool error: get resource timeout

### ISSUE THREAD

**Issue by jonesmz** [yandex/ozo#195]
I keep seeing ozo::error_code's with the following value and message.

`yamail::resource_pool::error::detail::category:1`

> get resource timeout

This is happening in the middle of my application's activities, where database activity is happening normally for several minutes already.

I'm using the default `ozo::connection_pool_config` settings.

I'm connecting to a database-as-a-service database in "the cloud", and have a pgBouncer load balance configured and managed by my service provider, so there shouldn't be any issues with connecting to the database, or a problem with limited number of connection slots available.

Could I get an explanation of possible causes for this error?

**Comment by thed636** [comment]
Hi Michael!

It looks like your application reached the pool capacity limit (which is 10 connections by default) and was timed-out while waiting in queue for a free connection. So you can increase the `capacity` number or your operation timeout (in-queue wait timeout is a part of) depending on your perferences.

**Comment by elsid** [comment]
Capacity limit is one thing, but another two are `queue_timeout` - how long is allowed to wait for a free connection and `queue_capacity` - how many requests are allowed to wait for a free connection. Since `connection_pool_timeouts` is deprecated I'm not sure how to adjust `queue_timeout`. `queue_capacity` is a part of `connection_pool_config`.

**Comment by elsid** [comment]
After reading https://github.com/yandex/ozo/commit/287d0ea91ea7e04803c61870e14aeda3fd489802 commit message, I'm confused. Is it now only a single timeout for operation that is propagated over all operations with deductions? What is rationale to have `bind_get_connection_timeout`? And this quote:

> since `queue` member would be ignored, rationale is that this time constrain should be equal to `connect` member

Does it mean `bind_get_connection_timeout` works both for queue and connection timeouts?

**Comment by thed636** [comment]
> Is it now only a single timeout for operation that is propagated over all operations with deductions?

Yes. For every operation the timeout will be converted to a deadline on start.  I tried to find real cases for the separate time constraints specification and found nothing. So I decided to simplify and unify interfaces with time constraint for the whole operation. The other reason is that without such simplification the failover mechanism implementation would be a very tricky thing with significantly more complicated interfaces. So that's the rationale for such decision.

> What is rationale to have `bind_get_connection_timeout`?

The main reason was to support legacy code. I do not think that it is really needed now. I think I should be deleted same as `connection_pool_timeouts` structure which is deprecated too. Currently I'm trying to reduce the number of the library entities just to make support, development and understanding easer.

> Does it mean `bind_get_connection_timeout` works both for queue and connection timeouts?

Yes. That's it. Since there is no way to determine will a connection be established or will the request be placed into queue, there is no reason to use different time constraints.

**Comment by jonesmz** [comment]
Can a single connection only be used for a single query at a time?

My application has the following query pattern.

On startup:
1. `ozo::execute` several table and function creation queries, happen in serial, not parallel.
2. `ozo::query` one query to fetch some server application configuration data.

During execution, devices connect to my server application. Each device connected triggers the following behavior
1. Every X seconds, query the database for updated device configuration, using `ozo::request` (This is per-device, and is a different type of configuration being retrieved than in the startup phase)
2. When the device sends telemetry data (arbitrary timing, but no less than 10 per minute, no more than 50 per minute), execute an `ozo::execute` to send that data to the database. This is the *overwhelming majority* of the database traffic for my application. 

I've seen "Startup Step 1" trigger this error, and I've also seen the error triggered in the post-startup phase.

Currently I only have a small number of devices in use (e.g. 10, this is on my testing server), and would not expect to see more than 10 connections be fully used, especially not if there's a 60 second long queue for acquiring a connection. Honestly, my initial expectation was that there would be barely enough database traffic to max out a single postgresql connection, especially since the application and database are co-located in the same data center. I'm very surprised that my application is able to trigger this outcome.

My expectation is that ozo is able to use a connection to execute multiple queries simultaneously, and execute the appropriate CompletionToken based on some internal Query ID that libpq's asynchronous query mode provides. Should I have a different expectation? Or am I using OZO incorrectly?

If a single connection can not provide multiple simultaneous async queries, what can I do with regards to using the libpq batch pipelining? The overwhelming majority of my database traffic is simply feeding information into the database, with no return values, which is extremely applicable to either async queries or batching / pipelining.

**Comment by jonesmz** [comment]
This how I'm using `ozo::execute`

```cpp
ozo::execute(m_connPool[m_ioc],
             ozo::make_query(static_telemetry_query_text,
                             m_telemetry_id_number,
                             m_clientID),
             [clientID = m_clientID](ozo::error_code ec, auto conn)
{
    if(ec)
    {
        LOG_MAIN(Error) << "Error encountered when executing query."
           << std::endl << "- Unit ID:         " << clientID
           << std::endl << "- ErrorCode:       " << ec
           << std::endl << "- OZO Error Msg:   " << ec.message()
           << std::endl << "- Libpq Error Msg: " << ozo::error_message(conn)
           << std::endl << "- Extra OZO Msg:   " << (  ozo::is_null_recursive(conn)
                                                     ? ""
                                                     : ozo::get_error_context(conn));
    }
});
```

As you can see, aside from logging success / failure, I don't care about the result, or need to wait on the result to continue executing the rest of my application. The vast majority of my database traffic is truly "set it and forget it".

**Comment by thed636** [comment]
> Can a single connection only be used for a single query at a time?

Yes. Only one query/transaction at a time per connection.

> My expectation is that ozo is able to use a connection to execute multiple queries simultaneously, 

AFAIK this is impossible due to the protocol and `PostgreSQL` architecture limitations. You should pay attention on the next thing. The external poolers give you an ability to share limited number of connections between clients via multiplexing, but anyway only one query/transaction per connection to the `postmaster` process may be executed at a time. The others **will wait** for free connections. E.g., if you have a limit for use 5 `postmaster` processes, it is no matter how many connections are established to a pooler no more than 5 queries or transactions will be executed simultaneously. If you send 10 queries via 10 connections to `pgpool`, only 5 of them will be executed, and the other 5 will wait for free connections to `postmaster`.

> If a single connection can not provide multiple simultaneous async queries, what can I do with regards to using the libpq batch pipelining?

Unfortunately no, the underlying `libpq` function `PQsendQueryParams` allows only one command in the query string. Multiple commands are allowed for `PQsendQuery` function but no parameters send.

> "set it and forget it".

The connection is busy at that moment, so you can forget, but the corresponding resource is still busy until your query execution have been finished, the positive result been received and callback is invoked. I'm a little bit surprising about operation time-out absence for the `execute` in your example - so the resource may be busy forever in some cases, like network problems and so on or take a significant time due to database busy or something similar.

> I've seen "Startup Step 1" trigger this error, and I've also seen the error triggered in the post-startup phase.

It looks like all the connections are busy at the moment. You can try to use `stat()` member function of `connection_pool` to get more information about current state of the pool object. 

And it should be very useful for you to get some statistics about:

* how long does it take to establish connection to the database (e.g., in case of TLS it could take a significant time), you can get this times via simple proxy object for `connection_info`;
* query execution timings.

With this statistics you can find the problem - not enough connections in the pool, or too small timeouts for operations. I'd love to have such embedded tools in the library, but unfortunately they are not ready yet.

**Comment by jonesmz** [comment]
Any support for batch mode?

https://2ndquadrant.github.io/postgres/libpq-batch-mode.html

**Comment by thed636** [comment]
Is it a custom extension of libpq from the Second Quadrant? I found nothing about batch mode in the official PostgreSQL documentation https://www.postgresql.org/docs/11/libpq.html could you point me at if I've just missed it?

**Comment by jonesmz** [comment]
Libpqxx calls this "pipelines" https://libpqxx.readthedocs.io/en/latest/a01025.html

I didn't think it was an extension. I was traveling and did not pay close attention to the URL I was providing.

**Comment by thed636** [comment]
Hi Michael!

According to the error. I've found the other case which was total forgotten. If you do not specify any time constraint for the operation which works with the connection pool to get a connection from, you will get a queue time-out error in case of all connections are busy. This is because of the time constraint absence being interpreted as a zero timeout for the connection pool wait queue. The reason is that there is no mechanism to control a handler placed in the underlying resource pool queue from outside. So in case of time constraint absence, it will be enqueued forever and a user could not cancel it using its own time constraint mechanism implementation. So your example demonstrates this behavior.

> Libpqxx calls this "pipelines" https://libpqxx.readthedocs.io/en/latest/a01025.html

I see. Thanks a lot for the information. I'm sorry but I can not answer you something concrete about plans to support it. The functionality is interesting but for today we do not need it for our internal projects which are the first-class citizens. Another problem is that it is not supported by the official `libpq` version and this is the necessary thing for now.

**Comment by jonesmz** [comment]
> This is because of the time constraint absence being interpreted as a zero timeout for the connection pool wait queue.

So I should provide a timeout for all of my `ozo::request` and `ozo::execute`  calls?

**Comment by jonesmz** [comment]
> I see. Thanks a lot for the information. I'm sorry but I can not answer you something concrete about plans to support it. The functionality is interesting but for today we do not need it for our internal projects which are the first-class citizens.

I understand

> Another problem is that it is not supported by the official libpq version and this is the necessary thing for now.

This is beyond surprising. I'm extremely confused that libpq doesn't have an official way to execute more than one query at a time other than to have multiple connections.

The obvious issue here is that even when sending queries to the server asynchronously, the application still has dead air on the network connection until the database replies with the result of the first query. At the very least, I would expect libpq to support sending multiple queries at a time, just to reduce the "dead-air" problem.

Thanks for considering the situation though.

**Comment by thed636** [comment]
> So I should provide a timeout for all of my ozo::request and ozo::execute calls?

Yes. In general it is the best practice to constrain your IO with a time-out. And if you want to limit a sequence of operations with some time-out e.g., to guarantee a response time of your service, you may use `ozo::deadline()` which produces `std::time_point` object as the deadline mark for all the sequence. In this case you should pass this `std::time_point` object as a time constraint for all operations from the sequence.

> This is beyond surprising. I'm extremely confused that libpq doesn't have an official way to execute more than one query at a time other than to have multiple connections.

As far as I understand this is the **PostgreSQL** architecture limit. Pipelines give an ability to reduce latency, but anyway all the queries will be serialized and executed on the backend one by one. I'm not surprised that this feature is not in the official version of `libpq`. From my point of view it makes the sophisticated and error-prone asynchronous protocol implementation even more sophisticated but the benefits are not so obvious. `libpq` is better than e.g., Oracle DB client library but unfortunately is still far from the state of the art.

**Comment by thed636** [comment]
> Thanks for considering the situation though.

Thanks for your questions.

**Comment by jonesmz** [comment]
For anyone reading along, I've implemented this functionality in an application-specific way, like such:

First, run SQL code similar to this:

```
CREATE OR REPLACE FUNCTION handle_telemetry_result_array(_ids TEXT[], _contents TEXT[])
RETURNS VOID AS
$BODY$
BEGIN
    IF ARRAY_LENGTH(_ids, 1) != ARRAY_LENGTH(_contents, 1) THEN
        RAISE invalid_parameter_value USING MESSAGE = 'Parameters must all be 1 dimensional arrays of equal length.';
    END IF;

    FOR i IN ARRAY_LOWER(_ids, 1) .. ARRAY_UPPER(_ids, 1)
    LOOP
        BEGIN
            PERFORM handle_telemetry_result(_ids[i], _contents[i]);
        EXCEPTION WHEN OTHERS THEN
            RAISE NOTICE 'Exception when running telemetry transaction for ID=%s, _ids[i];
        END;
    END LOOP;
END
$BODY$ LANGUAGE plpgsql;
```


Which takes several arrays of data points, which all must be the same length.

The function then iterates over each array, and executes your function of preference with the values provided.

In my case, the `handle_telemetry_result()` function looks up which function to execute based on the telemetryid that I provide, and executes it with the ID and contents provided.

Then, in your C++ code, something like this'll do the trick.

```
struct TelemetryDataController : std::enable_shared_from_this<TelemetryDataController>
{
    TelemetryDataController(boost::asio::io_context&                         ioc,
                            ozo::connection_pool<ozo::connection_info<>>&    connPool)
     : m_ioc(ioc)
     , m_connPool(connPool)
    { }

    void report_telemetry(std::string                clientID,
                          std::optional<std::string> content);
private:
    /**
     * @brief execute
     * If there is no data in flight, sends current data to the database.
     * Otherwise does nothing.
     */
    void execute(void);

private:
    boost::asio::io_context&                         m_ioc;
    ozo::connection_pool<ozo::connection_info<>>&    m_connPool;

    //Member variables that accumulate data while waiting for the current query to finish.
    std::vector<std::string>                m_ids;
    std::vector<std::optional<std::string>> m_contents;

    //Member variables with data that's in-flight to the database.
    std::vector<std::string>                m_inFlightIds;
    std::vector<std::optional<std::string>> m_inFlightContents;
};


void TelemetryDataController::report_telemetry(std::string                clientID,
                                               std::optional<std::string> content)
{
    m_macs.push_back(std::move(clientID));
    m_contents.push_back(std::move(content));

    execute();
} // TelemetryDataController::report_telemetry


//-----------------------------------------------------------------------------

void TelemetryDataController::execute(void)
{
    BOOST_ASSERT(m_ids.size() == m_contents.size());

    if(   m_ids.empty()
       || m_contents.empty())
    {
        return;
    }

    BOOST_ASSERT(m_inFlightIds.size() == m_inFlightContents.size());

    if(   ! m_inFlightIds.empty()
       || ! m_inFlightContents.empty())
    {
        return;
    }

    std::swap(m_ids,      m_inFlightIds);
    std::swap(m_contents, m_inFlightContents);

    auto callback = [this, pSelf = this->shared_from_this()](ozo::error_code ec, auto conn)
    {
        if(ec) { /* log failure, or take other action on failure */ }
        m_inFlightIds.clear();
        m_inFlightContents.clear();

        this->execute();
    };

    ozo::execute(m_connPool[m_ioc],
                 ozo::make_query("select handle_telemetry_result_array($1::TEXT[], $3::TEXT[])",
                                 // These are kept alive by callback holding ptr to TelemetryDataController
                                 std::ref(m_inFlightIds),
                                 std::ref(m_inFlightContents)),
                 // Adjust to be application specific, maybe grow with data items?
                 std::chrono::seconds(5),
                 std::move(callback));
} // TelemetryDataController::execute()
```

In this way, you only send data to the database when you don't already have a database operation in flight, and then as soon as that in-flight operation returns, another operation is triggered to send any data that has accumulated in the mean time.

Compared to simply having one DB connection per operation, this increases your average latency substantially. However, DB connections aren't free, and you're almost always limited to a small number of them, so it's generally worth the trade off if you're not very concerned about latency.

Is this a perfect solution? No, of course not. The only *real* solution to this problem is for libpq to gain the ability to use a single connection for multiple queries at the same time... even if the queries are all executed in serial on the database, just having less dead air is a substantial reduction in latency.

But that's out of the OZO library's control. So this is what I'm using until that feature is implemented.

**Comment by jonesmz** [comment]
> Is this a perfect solution? No, of course not. The only _real_ solution to this problem is for libpq to gain the ability to use a single connection for multiple queries at the same time... even if the queries are all executed in serial on the database, just having less dead air is a substantial reduction in latency.

Postgresql 14 now has this ability: https://lwn.net/Articles/870015/
