### ISSUE TITLE
Build requires all of PostgreSQL including server files.

### ISSUE THREAD

**Issue by ricejasonf** [yandex/ozo#214]
I'm building libpq from source, but your cmake configuration appears to require all of PostgreSQL.

It would be nice to only require the libpq client itself and not server related files.

Here are the errors:
```
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PostgreSQL (missing: PostgreSQL_TYPE_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindPostgreSQL.cmake:225 (find_package_handle_standard_args)
  CMakeLists.txt:11 (find_package)
```
I'm not sure if this should be pursued with CMake, or perhaps you would be willing to implement a workaround. (or maybe I should just be satisfied to build with the server files present)

**Comment by JonasProgrammer** [comment]
Hi,

this is the [normal behaviour](https://github.com/Kitware/CMake/blob/v3.16.0/Modules/FindPostgreSQL.cmake#L138) of CMake's `FindPostgreSQL.cmake` module. 

I'm not entirely sure as to why this is done ([line 248](https://github.com/Kitware/CMake/blob/v3.16.0/Modules/FindPostgreSQL.cmake#L248) lists this as a required var, but you are right, CMake would be the place to fix this.
Please note, however, that at least the installed version of ozo uses a vendored `FindPostgreSQL.cmake` from 3.14 instead (mostly, because 3.13 downwards did not define a target for Postgres), so if you get something done about this in upstream CMake, please inform us here as well, so we can fix the file accordingly.

P.S.: You don't need a full installation of PostgreSQL, at least for Debian based systems, the header CMake looks for is included in `postgresql-server-dev-11` (or whatever version you are using). Still, this does depend on some more packages, so some client programs of PostgreSQL will likely still be downloaded.

**Comment by ricejasonf** [comment]
Thank you for your response.

I'm building libpq from source and found in the docs how to get a minimal install for the client library only:
```
make
make -C src/include install
make -C src/interfaces install
```

I haven't actually used this in a program yet, but CMake's script appears to be satsified.

Sorry for the noise :sweat_smile:
