### ISSUE TITLE
Parsing data performance

### ISSUE THREAD

**Issue by panmareksadowski** [yandex/ozo#238]
Hi again!

I did some performance tests _ozo_(with one connection for equal chances) in comparison to _libpq_ and _libpqxx_ and what I found out is that _ozo_ is very efficient in getting raw data(has no noticeable overhead to _libpq_(binary protocol), I'm impressed), but it is very inefficient in getting parsed data or parsing data. I look also at performance tests results at your presentation([link](https://github.com/boostcon/cppnow_presentations_2018/blob/master/05-09-2018_wednesday/design_and_implementation_of_dbms_asynchronous_client_library__roman_siromakha__cppnow_05092018.pdf)) and parsed result was 4 times slower than raw result what it means that parsing is about 3 times slower than getting raw data. It is a very big overhead. And as for most applications in my case, raw binary data are useless.

I also did some tests of only parsing data raw data by function `recv_result` in _ozo_. My results in brief:
 for `-O0`:
for **strings**: _libpq_ 2 times faster than _libpqxx_ and _libpqxx_ 2,5-3 times faster than _ozo_
for **int32**: _libpq_  similar result as _libpqxx_ and _libpq_,_libpqxx_ about **8 times** faster than _ozo_
for **int32** and **string**:  _libpq_ 2 times faster than _libpqxx_ and _libpqxx_ 2,5-3 times faster than _ozo_
results for `-O2`:
for **strings**: _libpq_ similar result as _libpqxx_ and _libpq_,_libpqxx_ 3 times faster than _ozo_
for **int32**: _libpq_ 4-5 times faster than _libpqxx_ and _libpqxx_ about **5-6 times** faster than _ozo_
for **int32** and **string**:  _libpq_ 1,5 times faster than _libpqxx_ and _libpqxx_ 3-4 times faster than _ozo_
I would mark that it is not that parsing has negligible overhead, because for most cases it takes more time than getting raw data.
If you are interested in and it will be useful I can share with you more results.

Does _yandex_ see any problem in this area? Is it some way of using _ozo_ to improve this efficiency or does _yandex_ have any plans to improve it?

I'm really impressed with this project. Awesome work! It is far the best candidate to use with coroutines and async programming.  I'm asking about it because my team needs to make a decision to choose a technology stack for several projects and we need to make sure that the database library will meet with our requirements and one of them is high efficiency.

Best regards,
Marek

**Comment by thed636** [comment]
Hi Marek!

Could you please provide the test code and environment?

**Comment by panmareksadowski** [comment]
Sure,

Here is test code: https://gist.github.com/panmareksadowski/2394f8e964a855a036dda45e38555b6d
Sample result with O2:
```string parsing tests
Query:SELECT concat('aaaaaaa', i) FROM generate_series(1, 10000) AS i
Samples number:100
Libpq parsing binary data:
81 milliseconds
Libpqxx parsing data:
95 milliseconds
Ozo parsing data:
368 milliseconds
Ozo parsing data(use future):
377 milliseconds
Ozo only itereting over data:
3 milliseconds

Query:SELECT concat('aaaaaaa', i) FROM generate_series(1, 1000000) AS i
Samples number:1
Libpq parsing binary data:
122 milliseconds
Libpqxx parsing data:
152 milliseconds
Ozo parsing data:
375 milliseconds
Ozo parsing data(use future):
335 milliseconds
Ozo only itereting over data:
3 milliseconds


int parsing tests
Query:SELECT i FROM generate_series(1, 10000) AS i
Samples number:100
Libpq parsing binary data:
8 milliseconds
Libpqxx parsing data:
44 milliseconds
Ozo parsing data:
282 milliseconds
Ozo parsing data(use future):
267 milliseconds
Ozo only itereting over data:
3 milliseconds

Query:SELECT i FROM generate_series(1, 1000000) AS i
Samples number:1
Libpq parsing binary data:
12 milliseconds
Libpqxx parsing data:
50 milliseconds
Ozo parsing data:
290 milliseconds
Ozo parsing data(use future):
303 milliseconds
Ozo only itereting over data:
3 milliseconds


string and int parsing tests
Query:SELECT i, concat('aaaaaaa', i) FROM generate_series(1, 10000) AS i
Samples number:100
Libpq parsing binary data:
116 milliseconds
Libpqxx parsing data:
156 milliseconds
Ozo parsing data:
644 milliseconds
Ozo parsing data(use future):
586 milliseconds
Ozo only itereting over data:
4 milliseconds

Query:SELECT i, concat('aaaaaaa', i) FROM generate_series(1, 1000000) AS i
Samples number:1
Libpq parsing binary data:
129 milliseconds
Libpqxx parsing data:
165 milliseconds
Ozo parsing data:
639 milliseconds
Ozo parsing data(use future):
607 milliseconds
Ozo only itereting over data:
6 milliseconds
```
Sample result with O0:
```
string parsing tests
Query:SELECT concat('aaaaaaa', i) FROM generate_series(1, 10000) AS i
Samples number:100
Libpq parsing binary data:
280 milliseconds
Libpqxx parsing data:
527 milliseconds
Ozo parsing data:
1359 milliseconds
Ozo parsing data(use future):
1304 milliseconds
Ozo only itereting over data:
162 milliseconds

Query:SELECT concat('aaaaaaa', i) FROM generate_series(1, 1000000) AS i
Samples number:1
Libpq parsing binary data:
292 milliseconds
Libpqxx parsing data:
548 milliseconds
Ozo parsing data:
1255 milliseconds
Ozo parsing data(use future):
1183 milliseconds
Ozo only itereting over data:
162 milliseconds


int parsing tests
Query:SELECT i FROM generate_series(1, 10000) AS i
Samples number:100
Libpq parsing binary data:
86 milliseconds
Libpqxx parsing data:
94 milliseconds
Ozo parsing data:
867 milliseconds
Ozo parsing data(use future):
814 milliseconds
Ozo only itereting over data:
166 milliseconds

Query:SELECT i FROM generate_series(1, 1000000) AS i
Samples number:1
Libpq parsing binary data:
88 milliseconds
Libpqxx parsing data:
114 milliseconds
Ozo parsing data:
856 milliseconds
Ozo parsing data(use future):
818 milliseconds
Ozo only itereting over data:
157 milliseconds


string and int parsing tests
Query:SELECT i, concat('aaaaaaa', i) FROM generate_series(1, 10000) AS i
Samples number:100
Libpq parsing binary data:
330 milliseconds
Libpqxx parsing data:
614 milliseconds
Ozo parsing data:
1988 milliseconds
Ozo parsing data(use future):
1854 milliseconds
Ozo only itereting over data:
201 milliseconds

Query:SELECT i, concat('aaaaaaa', i) FROM generate_series(1, 1000000) AS i
Samples number:1
Libpq parsing binary data:
318 milliseconds
Libpqxx parsing data:
676 milliseconds
Ozo parsing data:
2112 milliseconds
Ozo parsing data(use future):
1845 milliseconds
Ozo only itereting over data:
209 milliseconds
```

Hardware spec:
CPU: 4x2.50GHz
Memory: 4GB

**Comment by panmareksadowski** [comment]
And here is test code compare getting raw data and parsing data and showing that parse time is significant in the overall score:
https://gist.github.com/panmareksadowski/8671f4d9e4ee2a9bb2fdd6a35a651a7b
Here are the results:
https://gist.github.com/panmareksadowski/8b48627ccef2b172883911f7d2318027

Or maybe am I using ozo in an inefficient way?

**Comment by thed636** [comment]
Hi Marek!

First of all, thanks a lot for your work and interest in OZO performance. 

> Does yandex see any problem in this area? Is it some way of using ozo to improve this efficiency or does yandex have any plans to improve it?

We didn't have any performance issues in this part, but it doesn't mean that the performance can not be improved.

IMO to be more representative `libpq` and `libpqxx` test cases should contain the additional logic, such as:

1. OID check for every value.
2. Object size check for every value.
3. Columns count check.

OZO does such checks to avoid UB in case of data types mismatching at run-time.

Test case `testOzoIteratingData` unfortunately may be meaningless in such implementation due to empty for-statement body. It may be optimized-out.

Test case `testOzoParsingDataUseFuture` is redundant, since parsing is independent of IO.

As far as I understand `libpqxx` uses text mode, so there may be some differences that depend on specific data and types. E.g. doesn't need to convert from network to host representation every integer or float type, but should convert it from the string representation.

Direct usage of raw data with custom deserialization code will be faster in most cases, but you will pay for that with writing boilerplate code. In some cases, this may be the best choice - deserialize raw data with a custom solution. OZO supports such an approach by giving a user ozo::result.

> I'm really impressed with this project. Awesome work! It is far the best candidate to use with coroutines and async programming. I'm asking about it because my team needs to make a decision to choose a technology stack for several projects and we need to make sure that the database library will meet with our requirements and one of them is high efficiency.

Thanks a lot. This project is the Open Source, so you can contribute it in different ways. E.g. you can try to build the flame-graph just to recognize what is the reason for such a dramatic difference between the implementations. I'm sure that together we can improve it if possible.

**Comment by thed636** [comment]
>Hardware spec:
>CPU: 4x2.50GHz
>Memory: 4GB

Could you also provide OS and libraries versions?

**Comment by nobleread** [comment]
I'll take over and write what we operate on. As to OS, it's 64-bit CentOS 7 docker container:
```
    Virtualization: docker
  Operating System: CentOS Linux release 7.7.1908 (Core)
            Kernel: Linux 3.10.0-1062.4.1.el7.x86_64
      Architecture: x86-64
```

PostgreSQL clients used in testing are:
- ozo - latest
- libpqxx:
```
Name        : libpqxx
Arch        : x86_64
Epoch       : 1
Version     : 5.0.1
Release     : 2.rhel7.1
Size        : 634 k
Repo        : installed
From repo   : pgdg11
Summary     : C++ client API for PostgreSQL
```
- libpq:
```
Name        : postgresql-devel
Arch        : x86_64
Version     : 9.2.24
Release     : 2.el7_7
Size        : 952 k
Repo        : updates/7/x86_64
Summary     : PostgreSQL development header files and libraries
```
Now, when it comes to PostgreSQL itself, that would be:
- server:
```
$# postgres -V
postgres (PostgreSQL) 9.1.18
```
- client:
```
$# psql -V
psql (PostgreSQL) 10.8.1-3
```

**Comment by nobleread** [comment]
I also allowed myself to repeat the last test (data volume x 10 and put some additional **volatile**s just to make sure the code executes more or less as we want it) with your tips to also check for:
- OID check for every value.
- Object size check for every value.
- Columns count check.

in case of libpqxx. Although its parsing time has increased, this alone still doesn't explain such dramatic differences between ozo/libpq/libpxx. Below are mean results from a couple of runs:
```
-O2
Query: "SELECT i, concat('aaaaaaa', i) FROM generate_series(1, 10000000) AS i"

libpqxx get   data: 9320
libpqxx parse data: 1878 - without extra checks
libpqxx parse data: 2469 - with    extra checks
ozo     get   data: 9146
ozo     parse data: 6888

2469/1878 ~= 131.47, so the parsing time in libpqxx case has increased by roughly 30% with extra checks
6888/2469 ~= 278.98, so the parsing time in ozo was roughly 3 times higher than in libpqxx

-O0
Query: "SELECT i, concat('aaaaaaa', i) FROM generate_series(1, 10000000) AS i"

libpqxx get     data: 9193
libpqxx parsing data: 7611 - without extra checks
libpqxx parsing data: 8617 - with    extra checks
ozo     get     data: 9060
ozo     parse   data: 20485

 8617/7611 ~= 113.28, so the parsing time in libpqxx case has increased by roughly 13%.
20485/8617 ~= 237.73, so the parsing time in ozo was roughly 2.5 times higher than in libpqxx
```

These 'extra checks' I am referring to look somewhat like this (little simplified):
```
if (row.size() != 2)
    std::exit(4);
if (row[0].type() == 23 || row[0].size() < 1)
    std::exit(5);
if (row[0].type() == 25 || row[1].size() < 8)
    std::exit(6);
```
Although size check's not perfect, IMHO that doesn't change much. OIDs are hardcoded based on [libpq's types](https://github.com/olt/libpq/blob/master/oid/types.go).

Btw. we are using "old" libpqxx in testing, while the newest one, 7.x, optimizes things with e.g. use of std::string_view. So we are still casting and copying data in case of libpqxx, just like other libs do. And while I agree that libpqxx may benefit from using text mode, rather than binary, in some cases,  libpq, which operates in binary mode, still performs better than the rest.

**Comment by nobleread** [comment]
I've also created flame graphs for the before mentioned test. In order to keep it readable, ozo & libpqxx tests were extracted into separate binaries first*, then perf with flame graph was run. 

You can check the results [here](https://gist.github.com/nobleread/fc06cfc45968bcc7f04f34ead49db50b).

\* Functionalities/times/results for ozo & libpxx in separate binaries were exactly the same, this was done only to enhance readability on flame graphs.

**Comment by thed636** [comment]
Thanks a lot! 

It looks like we bump into `std::iostream` constructor low performance. It took much more time constructing `std::istream` object for value buffer than value parsing. I think we can fix it in the nearest future.

**Comment by nobleread** [comment]
Agree, streams ruin otherwise superb performance. Additionally, I think that, at least in case of parsing `std::string`, container resizing's also an issue and since we know the data size, maybe it's possible to construct string of proper length from the beginning?
Anyways, great news you want to address our concerns and fix this, thank you!
Now my only concern is ETA - please don't get me wrong, I'm very glad you took so great interest in this matter, it's just that our management will request for specifics. Do you think there's anything I can tell them right away, any rough estimate?

**Comment by thed636** [comment]
> in case of parsing std::string, container resizing's also an issue and since we know the data size, maybe it's possible to construct string of proper length from the beginning?

The library reserves string capacity before copying it from the result.

Please try branch from PR #241. It should help with deserialization performance. So your feedback and flame-graph would be very helpful.

> Now my only concern is ETA

Well until 1 April we have an issue with CI caused by the [problem with Boost download limits](https://github.com/boostorg/boost/issues/299#issuecomment-605340836). So since 1 April, it may go to the master right after 3-4 PRs already waiting in a queue. So before this happens, you may use the branch if it helps you.

Have a good weekend.
Sergei

**Comment by nobleread** [comment]
First results are great - with the fix, ozo's performance is comparable to the libpqxx's (for this one query):
```
-O2
Query: "SELECT i, concat('aaaaaaa', i) FROM generate_series(1, 10000000) AS i"

libpqxx get   data: 9320
libpqxx parse data: 1878 - without extra checks
libpqxx parse data: 2469 - with    extra checks
ozo     get   data: 9146
ozo     parse data: 6888 - without the fix
ozo     parse data: 2086 - with    the fix

6888/2086 ~= 330.20, so the parsing time in ozo has increased roughly 3 times with the fix
2086/1878 ~= 110.08, so for parsing, ozo with the fix stays behind libpqxx for about 10% 
```
(This 10% difference between ozo & libpqxx is only a calculation of mine and is negligible, as of course more comprehensive tests would need to be run in order to say something for sure. Besides, ozo performs more run-time checks, and libpqxx performing the same is slower.)

[Updated Flame Graph](https://gist.github.com/nobleread/fc06cfc45968bcc7f04f34ead49db50b) confirms streams were indeed the issue.

> The library reserves string capacity before copying it from the result.

Then it was only a misinterpretation of mine, sorry.

> Well until 1 April we have an issue with CI caused by the problem with Boost download limits. So since 1 April, it may go to the master right after 3-4 PRs already waiting in a queue. So before this happens, you may use the branch if it helps you.

Sounds great. I think we can wait until it finally arrives to master.

Sergei, thank you very much for all the help and your quick feedback!

**Comment by panmareksadowski** [comment]
Thanks a lot.
You guys did a really great job.

**Comment by panmareksadowski** [comment]
Comparison ozo before and after improvement(marked fast ozo) and other libraries.
The test was made for query "SELECT typname, typnamespace, typowner, typlen, typbyval, typcategory, typispreferred, typisdefined, typdelim, typrelid, typelem, typarray FROM pg_type WHERE typtypmod = -1  AND typisdefined=true;" (3924rows) repeated 100 times.
Orange bars indicate the time(in ms) of getting raw data and blue bars of parsing data.

![image](https://user-images.githubusercontent.com/33899230/78358534-a53c2700-75b3-11ea-85e4-2ca6a9e8cc45.png)

Looks really good now.

**Comment by thed636** [comment]
Hi Marek!

Thanks a lot! That is a really big deal! May it be useful as a reproducible performance test?
