### ISSUE TITLE
CMakeLists.txt generates unstable package target

### ISSUE THREAD

**Issue by JonasProgrammer** [yandex/ozo#280]
Hi,

I stumbled upon a minor issue with the current `CMakeLists.txt` when reviewing generated package files: The `ozo` CMake targets being exported from the library conditionally define a couple of warning flags, depending on the compiler used for packaging.
[These lines](https://github.com/yandex/ozo/blob/8a6597623816cbda63f329ff765ba2db95059c88/CMakeLists.txt#L30) are responsible for this.

As to why this is an issue: First of all, including warning flags in exported targets at all is a debatable practise. Second, despite being header-only, the packaged version's cmake files (to be consumed by external projects) slightly differ, depending on which compiler was used *during packaging* -- with the warnings being included, if clang was present or absent, if any other compiler was used.

This is not an issue when you use ozo as a submodule or pull it in via `ExternalProject_add`, which is what you do at yandex, I presume. Still, for the use case of an external package, a stable build output regardless of the compiler present on the packaging system (if any) would be desirable, so it can be copied and consumed to other system configurations.

I think simply putting the offending options in a generator expression, so it is only picked up during build time, and then mirroring the behaviour in `cmake/ozo-config.cmake` should do the trick, but I'd need to have a closer look at this.

**Comment by elsid** [comment]
I agree this is an issue. The problem is that ozo can't be build by Clang with `-Werror` and without `-Wno-gnu-string-literal-operator-template -Wno-gnu-zero-variadic-macro-arguments` in the current state. With GCC >= 9 it's also not possible but there are no similar to flags to Clang. So first we need to provide a way to build it by default without usage of string literal operator templates. One possible solution is to provide a marco like Boost.Hana [does](https://www.boost.org/doc/libs/1_75_0/libs/hana/doc/html/structboost_1_1hana_1_1string.html#a7f15faa77e126e1c2b08a2224ceefb84).

Regadrind the build system at Yandex. They don't use CMake, at least when I started to use ozo we had ya.make build system, you may find examples how it's used in [catboost](https://github.com/catboost/catboost/blob/master/catboost/app/ya.make) project. So basically everything CMake related is not for Yandex internal usage.

**Comment by JonasProgrammer** [comment]
Ok, thank you for the insight. Adding warning options to the libraries interface is still a little debatable (after all, building with `-Werror` is up to the consumer), but I agree the current behavior should be retained and kept, as it is what's 'out there'.

I'll see if I can make this work so it is determined during configuration time when consuming the package, however, rather than relying on the packager's compiler being the same as the package consumer's.
