### ISSUE TITLE
Does Ozo support LTREE type

### ISSUE THREAD

**Issue by neogenie** [yandex/ozo#291]
Does Ozo support `LTREE` type: https://www.postgresql.org/docs/9.1/ltree.html ?

**Comment by neogenie** [comment]
Since PostgreSQL 13 ltree supported in binary protocol: https://postgrespro.com/list/id/E1jJkxu-0005HI-SY@gemulon.postgresql.org. Details of implementation: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=949a9f043eb70a4986041b47513579f9a13d6a33

The problem, as I understand it, is that the ltree has a dynamic oid. I've solved this issue by this code:

```c++
#include <string>

#include <ozo/io/recv.h>
#include <ozo/io/send.h>
#include <ozo/pg/definitions.h>

class ltree
{
  friend ozo::send_impl<ltree>;
  friend ozo::recv_impl<ltree>;
  friend ozo::size_of_impl<ltree>;

public:
  ltree() = default;

  explicit ltree(std::string data) : m_data(std::move(data)) {}

  [[nodiscard]] const std::string& getData() const& noexcept { return m_data; }
  std::string&& getData() && noexcept { return std::move(m_data); }

private:
  std::string m_data;
};

namespace ozo {

template<>
struct size_of_impl<ltree> {
  static auto apply(const ltree& v) noexcept { return std::size(v.m_data) + 1; }
};

template<>
struct send_impl<ltree> {
  template<typename OidMap>
  static ostream& apply(ostream& out, const OidMap&, const ltree& in) {
    const std::int8_t version = 1;
    write(out, version);
    return write(out, in.m_data);
  }
};

template<>
struct recv_impl<ltree> {
  template<typename OidMap>
  static istream& apply(istream& in, size_type size, const OidMap&, ltree& out) {
    if (size < 1) {
      throw std::range_error("data size " + std::to_string(size) + " is too small to read ltree");
    }

    std::int8_t version = 1;
    read(in, version);
    out.m_data.resize(static_cast<std::size_t>(size - 1));
    return read(in, out.m_data);
  }
};

}  // namespace ozo

OZO_PG_DEFINE_CUSTOM_TYPE(ltree, "ltree");
OZO_PG_DEFINE_CUSTOM_TYPE(std::vector<ltree>, "ltree[]");
```

I could format this as a pull request, but as I understand it, the library only supports static types with a fixed oids. @thed636

**Comment by thed636** [comment]
Hi Neo! 

> I could format this as a pull request

Thanks a lot! PRs are always welcome here!  The only suggestion is to be more conform with the very similar `jsonb` implementation in terms of renaming `getData()` to  `raw_string()`. Integration tests and unit-tests are needed as well. Since this will be your first PR in the project, you should add yourself into [AUTHORS](https://github.com/yandex/ozo/blob/master/AUTHORS) file as a contributor.

> the library only supports static types with a fixed oids

The library supports dynamic oids. For the dynamic oid types, a user should register a type (as well as array representation) in the types oid map by means of [ozo::register_types](https://yandex.github.io/ozo/group__group-type__system-functions.html#ga1a61e0dca7ca89483750958ebe4a51bc). In this case the library will request the necessary oids during establishing a connection to a database. 

> OZO_PG_DEFINE_CUSTOM_TYPE(std::vector<ltree>, "ltree[]");

No needs to define the array type. It will be managed automatically during `ozo::register_types<std::vector<ltree>, ...>()` call.

**Comment by neogenie** [comment]
I made a #292 in accordance with your requirements. @thed636 @elsid
